### ISSUE TITLE
Books.gen only looks for code in md files under contents folder

### ISSUE THREAD

**Issue by findmyway** [rikhuijzer/Books.jl#72]
I'm not sure if this is intentional. The code snippets included in the `index.md` file are ignored. It seems 

https://github.com/rikhuijzer/Books.jl/blob/f14573f4b614959e4aec5e908cd68738f303fd5d/src/generate.jl#L140

doesn't take the `index.md` into account.

**Comment by rikhuijzer** [comment]
It is sort of intentional, yes. The `index.md` contents are not shown in the PDF, so I didn't think it would be important to run the code from it via `Books.gen`. This is based on the index pages for R books, such as https://adv-r.hadley.nz/. At those pages, Hadley Wickham also doesn't show generated content on the front page.

However, it might be a good idea to allow it. What kinds of things do you want to show at the front page?

**Comment by findmyway** [comment]
I see. I was to add an instruction on which version of Julia the book is built with. Never mind, I can just hard code it there.

**Comment by rikhuijzer** [comment]
> I see. I was to add an instruction on which version of Julia the book is built with. Never mind, I can just hard code it there.

But then the Julia version is not reported in the PDF. Still, there are probably situations where this issue is a good idea, so I might still implement it later. 

By the way, today I was working on my own book and realized that showing code blocks and the output was super cumbersome. Checkout the newest version for some (I think) awesome changes! You can use `_gen/foo_bar-sco.md` now to show code and output. See the docs for more info.

**Comment by findmyway** [comment]
Pretty nice!
